### PR TITLE
Fix build on FreeBSD (tag 0.14-rc3)

### PR DESCRIPTION
**Pull request by johalun**
Not sure about the timer comparison error. Getting this with clang 4.0.0: 
```
/home/johannes/dev/sway/swaybar/event_loop.c:102:24: error: comparison of distinct pointer types
      ('timer_t' (aka 'struct __timer *') and 'const timer_t *' (aka 'struct __timer *const *'))
      [-Werror,-Wcompare-distinct-pointer-types]
        if (timer_item->timer == timer) {
```
Are we comparing pointers or objects?

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Pointers, in this case. Thanks!

**Comment by johalun** [comment]
Sorry my question was confusing since its a double pointer :) 
Is my PR correct or should we take address of lhs object?  i.e.
 ` if (&timer_item->timer == timer) `

**Comment by SirCmpwn** [comment]
iiuc *timer is right.

**Comment by SirCmpwn** [comment]
cc @4e554c4c

**Comment by johalun** [comment]
Ok. Yeah makes more sense.

**Comment by SirCmpwn** [comment]
Can you retarget this against master and rebase? Will fix the build and I'll cherry-pick your commit into 0.14.

**Comment by 4e554c4c** [comment]
Yep, `timer_item` holds a `timer_t` not a `timer_t *`. This should be right.

**Comment by SirCmpwn** [comment]
Bump. 0.14-rc4 is going to be 2 days late now, I'd like to get this change in.

**Comment by johalun** [comment]
Closing this in favor of new PR.
